apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ib-gateway.fullname" . }}
  labels:
    {{- include "ib-gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ib-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ib-gateway.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "ib-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: '{{ include "ib-gateway.fullname" . }}'
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: IB_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: {{ include "ib-gateway.fullname" . }}-credentials
                  key: ib-account-id
            - name: IB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ib-gateway.fullname" . }}-credentials
                  key: ib-account-pwd
            - name: TRADING_MODE
              valueFrom:
                secretKeyRef:
                  name: {{ include "ib-gateway.fullname" . }}-credentials
                  key: ib-trading-mode
          ports:
            - name: gateway
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            exec:
              command:
                - /healthcheck/bin/healthcheck
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            exec:
              command:
                - /healthcheck/bin/healthcheck
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          startupProbe:
            exec:
              command:
                - /healthcheck/bin/healthcheck
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
